// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskList.Infrastructure.Persistance;

#nullable disable

namespace TaskList.Infrastructure.PostgreSql.Migrations
{
    [DbContext(typeof(TaskListContext))]
    partial class TaskListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TaskList.Domain.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("TaskID")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskID");

                    b.ToTable("Comment");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e90dfaf-45d0-434d-9b10-1968f323d8e6"),
                            Content = "Комментарий 1 к задаче Задача 1 листа Первый список задач",
                            TaskID = new Guid("eceec90e-5144-4f28-808d-c7f2c1bef010")
                        },
                        new
                        {
                            Id = new Guid("6ae6b928-6288-4170-bc04-737f153c3eb1"),
                            Content = "Комментарий 1 к задаче Задача 2 листа Первый список задач",
                            TaskID = new Guid("de889a60-0f47-4341-acce-2414514d91a8")
                        },
                        new
                        {
                            Id = new Guid("c4c162fb-f3fd-4d27-be62-ec85cb790888"),
                            Content = "Комментарий 2 к задаче Задача 2 листа Первый список задач",
                            TaskID = new Guid("de889a60-0f47-4341-acce-2414514d91a8")
                        },
                        new
                        {
                            Id = new Guid("a6e7c697-9ffe-4f31-a936-99a0c6ac6940"),
                            Content = "Комментарий 1 к задаче Задача 3 листа Первый список задач",
                            TaskID = new Guid("bd3cf78d-82c4-4bd3-b575-76ae7a4b9197")
                        },
                        new
                        {
                            Id = new Guid("ac9be2c7-c982-456b-8a56-74374c8f30f2"),
                            Content = "Комментарий 2 к задаче Задача 3 листа Первый список задач",
                            TaskID = new Guid("bd3cf78d-82c4-4bd3-b575-76ae7a4b9197")
                        },
                        new
                        {
                            Id = new Guid("65e2c31a-42f4-476c-8994-5ea0d8c5a454"),
                            Content = "Комментарий 1 к задаче Задача 4 листа Первый список задач",
                            TaskID = new Guid("c5607256-205a-48c7-8b4f-c7fa4bd684cc")
                        },
                        new
                        {
                            Id = new Guid("faa74b26-c261-4749-9c1e-6fb4253e9bdb"),
                            Content = "Комментарий 2 к задаче Задача 4 листа Первый список задач",
                            TaskID = new Guid("c5607256-205a-48c7-8b4f-c7fa4bd684cc")
                        },
                        new
                        {
                            Id = new Guid("34a4ddce-02b6-45db-85ff-f92254ad3a61"),
                            Content = "Комментарий 1 к задаче Задача 5 листа Первый список задач",
                            TaskID = new Guid("5561d361-33ba-4bf0-8c9d-f5f035bf9807")
                        },
                        new
                        {
                            Id = new Guid("9911d738-039f-4ec7-81b9-0c428ea6f2cd"),
                            Content = "Комментарий 1 к задаче Задача 6 листа Первый список задач",
                            TaskID = new Guid("a19cff3c-921f-4b73-b482-27aca75eaae3")
                        },
                        new
                        {
                            Id = new Guid("ad530a93-867d-4415-a9d0-989085a201ce"),
                            Content = "Комментарий 2 к задаче Задача 6 листа Первый список задач",
                            TaskID = new Guid("a19cff3c-921f-4b73-b482-27aca75eaae3")
                        },
                        new
                        {
                            Id = new Guid("61030ea7-17ca-4dab-a394-0da6b353339b"),
                            Content = "Комментарий 1 к задаче Задача 7 листа Первый список задач",
                            TaskID = new Guid("6b4bbae9-2200-49b7-8f2f-d1f240050cec")
                        },
                        new
                        {
                            Id = new Guid("91706fb3-5df6-4da2-a23a-ce088bf943b3"),
                            Content = "Комментарий 2 к задаче Задача 7 листа Первый список задач",
                            TaskID = new Guid("6b4bbae9-2200-49b7-8f2f-d1f240050cec")
                        },
                        new
                        {
                            Id = new Guid("56adc2bf-a70d-4bd3-9741-f05d9b1f64dd"),
                            Content = "Комментарий 1 к задаче Задача 8 листа Первый список задач",
                            TaskID = new Guid("6e17e8f2-620e-4bab-b4b2-971d1acc9be2")
                        },
                        new
                        {
                            Id = new Guid("6bed42f4-7c2d-4ff5-8a7c-e0a61f2c0b6d"),
                            Content = "Комментарий 1 к задаче Задача 9 листа Первый список задач",
                            TaskID = new Guid("865430dd-32fe-4673-93db-f18a29e9a1b8")
                        },
                        new
                        {
                            Id = new Guid("a64f055e-bd3f-4d28-acc9-501f0dbf6fdb"),
                            Content = "Комментарий 1 к задаче Задача 10 листа Первый список задач",
                            TaskID = new Guid("88f9453d-301b-4f3f-a1f7-50087e98c3c5")
                        },
                        new
                        {
                            Id = new Guid("6c9f0f72-962d-4c76-9c19-90c9d5037754"),
                            Content = "Комментарий 1 к задаче Задача 1 листа Второй список задач",
                            TaskID = new Guid("d4e7ff20-43dd-430d-9fcb-ad8523f62b0c")
                        },
                        new
                        {
                            Id = new Guid("46c0dbc8-26ab-40f0-b08c-90632efce36e"),
                            Content = "Комментарий 2 к задаче Задача 1 листа Второй список задач",
                            TaskID = new Guid("d4e7ff20-43dd-430d-9fcb-ad8523f62b0c")
                        },
                        new
                        {
                            Id = new Guid("923b6f75-9162-46c0-84cd-5acc2156abb0"),
                            Content = "Комментарий 1 к задаче Задача 2 листа Второй список задач",
                            TaskID = new Guid("86bab430-5e0a-4f62-9163-aeeb7aa9bc2a")
                        },
                        new
                        {
                            Id = new Guid("404b4055-1684-4402-84f5-a1e90f75189f"),
                            Content = "Комментарий 2 к задаче Задача 2 листа Второй список задач",
                            TaskID = new Guid("86bab430-5e0a-4f62-9163-aeeb7aa9bc2a")
                        },
                        new
                        {
                            Id = new Guid("5f457cb2-de0d-4184-b760-9ea8d3d1bf58"),
                            Content = "Комментарий 1 к задаче Задача 3 листа Второй список задач",
                            TaskID = new Guid("17591683-782c-4440-878a-7e286081a81e")
                        },
                        new
                        {
                            Id = new Guid("563c54a2-06fd-446e-a9aa-81c0097b2e4c"),
                            Content = "Комментарий 2 к задаче Задача 3 листа Второй список задач",
                            TaskID = new Guid("17591683-782c-4440-878a-7e286081a81e")
                        },
                        new
                        {
                            Id = new Guid("ddb31317-5116-4e1f-ae68-dc1f1037f9ed"),
                            Content = "Комментарий 1 к задаче Задача 4 листа Второй список задач",
                            TaskID = new Guid("a458d036-0f19-49cd-91ff-5ce9b7a19bc8")
                        },
                        new
                        {
                            Id = new Guid("c3539a00-2355-445b-b73d-deafb9b75bdf"),
                            Content = "Комментарий 2 к задаче Задача 4 листа Второй список задач",
                            TaskID = new Guid("a458d036-0f19-49cd-91ff-5ce9b7a19bc8")
                        },
                        new
                        {
                            Id = new Guid("291d7479-1524-47dc-a08e-4294b7b6db76"),
                            Content = "Комментарий 1 к задаче Задача 5 листа Второй список задач",
                            TaskID = new Guid("599bab9c-6cb8-4196-9ceb-9afc74254247")
                        },
                        new
                        {
                            Id = new Guid("2990667d-0a6b-466e-875a-29a3cd3a6f06"),
                            Content = "Комментарий 2 к задаче Задача 5 листа Второй список задач",
                            TaskID = new Guid("599bab9c-6cb8-4196-9ceb-9afc74254247")
                        },
                        new
                        {
                            Id = new Guid("8f2385ab-1127-40c6-a498-30a28a4522cf"),
                            Content = "Комментарий 1 к задаче Задача 6 листа Второй список задач",
                            TaskID = new Guid("ed207dfa-d8ed-40f9-be96-24d5be74c9a9")
                        },
                        new
                        {
                            Id = new Guid("ae0e52ca-ea4a-4a98-a1c2-1392d8c77969"),
                            Content = "Комментарий 2 к задаче Задача 6 листа Второй список задач",
                            TaskID = new Guid("ed207dfa-d8ed-40f9-be96-24d5be74c9a9")
                        },
                        new
                        {
                            Id = new Guid("22e9a69a-f940-4532-a14b-134111bd2f98"),
                            Content = "Комментарий 1 к задаче Задача 7 листа Второй список задач",
                            TaskID = new Guid("939eb2d4-439c-4491-956d-82b639aa42bc")
                        },
                        new
                        {
                            Id = new Guid("d7bc58da-8178-4442-958e-0bd0d06ce5d9"),
                            Content = "Комментарий 2 к задаче Задача 7 листа Второй список задач",
                            TaskID = new Guid("939eb2d4-439c-4491-956d-82b639aa42bc")
                        },
                        new
                        {
                            Id = new Guid("d86910e8-b5c0-47f4-97f5-5e4e5eb26990"),
                            Content = "Комментарий 1 к задаче Задача 8 листа Второй список задач",
                            TaskID = new Guid("76e0e6b2-932e-450e-b944-86ccb7ff0bff")
                        },
                        new
                        {
                            Id = new Guid("6b32ee15-ae69-4a99-b52e-45b2f81b59c4"),
                            Content = "Комментарий 1 к задаче Задача 9 листа Второй список задач",
                            TaskID = new Guid("4ef740ed-732e-4ca1-b404-80678ba6cbc1")
                        },
                        new
                        {
                            Id = new Guid("e38e502b-331f-470e-b6a0-172a373e991d"),
                            Content = "Комментарий 2 к задаче Задача 9 листа Второй список задач",
                            TaskID = new Guid("4ef740ed-732e-4ca1-b404-80678ba6cbc1")
                        },
                        new
                        {
                            Id = new Guid("6a1114ad-32ac-4dfa-bb13-fd0e983a127b"),
                            Content = "Комментарий 1 к задаче Задача 10 листа Второй список задач",
                            TaskID = new Guid("f5a697d1-b2bf-40c9-863b-6bd43d27595d")
                        },
                        new
                        {
                            Id = new Guid("6d242961-7a08-4c30-be08-e3b8fe9c69ef"),
                            Content = "Комментарий 2 к задаче Задача 10 листа Второй список задач",
                            TaskID = new Guid("f5a697d1-b2bf-40c9-863b-6bd43d27595d")
                        },
                        new
                        {
                            Id = new Guid("ebaf3dd8-7f4a-4423-b745-c942e462bde2"),
                            Content = "Комментарий 1 к задаче Задача 1 листа Третий список задач",
                            TaskID = new Guid("7de0edfc-5e64-4d14-b38b-f5c0ba5ea34c")
                        },
                        new
                        {
                            Id = new Guid("940453a3-5a90-4cfa-ac51-6141fce7d1fe"),
                            Content = "Комментарий 2 к задаче Задача 1 листа Третий список задач",
                            TaskID = new Guid("7de0edfc-5e64-4d14-b38b-f5c0ba5ea34c")
                        },
                        new
                        {
                            Id = new Guid("cbfdc8d5-e382-4a28-b7d8-50b0500b4058"),
                            Content = "Комментарий 1 к задаче Задача 2 листа Третий список задач",
                            TaskID = new Guid("a68c09fe-11e3-4a52-b76b-b56151ea4a35")
                        },
                        new
                        {
                            Id = new Guid("a266369e-6f54-445f-a160-b62ce8f2c9e9"),
                            Content = "Комментарий 1 к задаче Задача 3 листа Третий список задач",
                            TaskID = new Guid("7d9fdaf5-e7c4-4d91-aa1f-31bf51571c3a")
                        },
                        new
                        {
                            Id = new Guid("836be0e7-0aab-4e2e-91d5-69ef0175061c"),
                            Content = "Комментарий 2 к задаче Задача 3 листа Третий список задач",
                            TaskID = new Guid("7d9fdaf5-e7c4-4d91-aa1f-31bf51571c3a")
                        },
                        new
                        {
                            Id = new Guid("3cd62217-e70e-4721-bfc6-cc16bbec3698"),
                            Content = "Комментарий 1 к задаче Задача 4 листа Третий список задач",
                            TaskID = new Guid("ea83e531-7985-4341-afdf-be9d43e79bfc")
                        },
                        new
                        {
                            Id = new Guid("2a0ce373-bbe6-48be-ab58-90262943f065"),
                            Content = "Комментарий 2 к задаче Задача 4 листа Третий список задач",
                            TaskID = new Guid("ea83e531-7985-4341-afdf-be9d43e79bfc")
                        },
                        new
                        {
                            Id = new Guid("fd5df444-1465-4322-8003-74b6a5c7b4c8"),
                            Content = "Комментарий 1 к задаче Задача 5 листа Третий список задач",
                            TaskID = new Guid("a182168e-d522-4a08-b2d4-96080f7a80b8")
                        },
                        new
                        {
                            Id = new Guid("53f4be9d-bb46-4c17-b9db-66855e8ab1d7"),
                            Content = "Комментарий 2 к задаче Задача 5 листа Третий список задач",
                            TaskID = new Guid("a182168e-d522-4a08-b2d4-96080f7a80b8")
                        },
                        new
                        {
                            Id = new Guid("0ccc3c22-4205-4b93-9185-44bef009118d"),
                            Content = "Комментарий 1 к задаче Задача 6 листа Третий список задач",
                            TaskID = new Guid("d8093abf-dcd5-449a-8754-f90c34fb3982")
                        },
                        new
                        {
                            Id = new Guid("90fb58e8-f731-4deb-ad3a-f79e49232a5d"),
                            Content = "Комментарий 2 к задаче Задача 6 листа Третий список задач",
                            TaskID = new Guid("d8093abf-dcd5-449a-8754-f90c34fb3982")
                        },
                        new
                        {
                            Id = new Guid("2a43a44d-2089-4e2f-bec7-60ab2d765676"),
                            Content = "Комментарий 1 к задаче Задача 7 листа Третий список задач",
                            TaskID = new Guid("6457f588-6bf7-413f-9685-70ffd90e6ba6")
                        },
                        new
                        {
                            Id = new Guid("0e23c4e2-c65c-4018-947d-8f732863584c"),
                            Content = "Комментарий 1 к задаче Задача 8 листа Третий список задач",
                            TaskID = new Guid("a47b01b1-c7dc-4766-8f3c-ea0451b91741")
                        },
                        new
                        {
                            Id = new Guid("b78b4347-b82e-4f95-aa3f-4878f96b9e42"),
                            Content = "Комментарий 2 к задаче Задача 8 листа Третий список задач",
                            TaskID = new Guid("a47b01b1-c7dc-4766-8f3c-ea0451b91741")
                        },
                        new
                        {
                            Id = new Guid("d61ed73c-6dc1-4f0a-9e8e-00c9075337d8"),
                            Content = "Комментарий 1 к задаче Задача 9 листа Третий список задач",
                            TaskID = new Guid("8541f399-22c4-4f04-a928-612b4a37edab")
                        },
                        new
                        {
                            Id = new Guid("583606dd-edbc-4419-a985-4e0ebb74972c"),
                            Content = "Комментарий 1 к задаче Задача 10 листа Третий список задач",
                            TaskID = new Guid("24ce9f1c-0f6e-4c26-bf40-624535ec8730")
                        },
                        new
                        {
                            Id = new Guid("442a5cf3-d04d-472d-bf4f-57c1cacfbafa"),
                            Content = "Комментарий 2 к задаче Задача 10 листа Третий список задач",
                            TaskID = new Guid("24ce9f1c-0f6e-4c26-bf40-624535ec8730")
                        });
                });

            modelBuilder.Entity("TaskList.Domain.Entities.StatusTaskHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("StatusTaskHistory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("88aa703e-9dcc-48e0-ad49-52e8b1fc752c"),
                            AddDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("eceec90e-5144-4f28-808d-c7f2c1bef010")
                        },
                        new
                        {
                            Id = new Guid("55f0ab14-f76e-49d2-99b8-facc5b44efce"),
                            AddDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("de889a60-0f47-4341-acce-2414514d91a8")
                        },
                        new
                        {
                            Id = new Guid("634a0607-68ec-443f-b022-99843974c434"),
                            AddDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("bd3cf78d-82c4-4bd3-b575-76ae7a4b9197")
                        },
                        new
                        {
                            Id = new Guid("1779c213-bdbc-4d06-9e50-7a4e210886b5"),
                            AddDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("c5607256-205a-48c7-8b4f-c7fa4bd684cc")
                        },
                        new
                        {
                            Id = new Guid("345d2c72-1e1b-43ba-b404-6779edbe2fc0"),
                            AddDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("5561d361-33ba-4bf0-8c9d-f5f035bf9807")
                        },
                        new
                        {
                            Id = new Guid("20c09be9-e996-46c1-aaeb-b06dc59dd2a5"),
                            AddDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("a19cff3c-921f-4b73-b482-27aca75eaae3")
                        },
                        new
                        {
                            Id = new Guid("88f3f476-1d47-4574-a1ff-7f5d8422c11b"),
                            AddDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("6b4bbae9-2200-49b7-8f2f-d1f240050cec")
                        },
                        new
                        {
                            Id = new Guid("a7a574f3-8e29-4d57-9fa7-efb23ff0ca1f"),
                            AddDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("6e17e8f2-620e-4bab-b4b2-971d1acc9be2")
                        },
                        new
                        {
                            Id = new Guid("cd6548c8-055d-4298-917a-1f3f7cb23986"),
                            AddDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("865430dd-32fe-4673-93db-f18a29e9a1b8")
                        },
                        new
                        {
                            Id = new Guid("e8f029a3-0d2b-4403-a44d-501753b02230"),
                            AddDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("88f9453d-301b-4f3f-a1f7-50087e98c3c5")
                        },
                        new
                        {
                            Id = new Guid("3bf4f338-62a3-4be8-a05c-96f491c222bb"),
                            AddDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("d4e7ff20-43dd-430d-9fcb-ad8523f62b0c")
                        },
                        new
                        {
                            Id = new Guid("a2eab4f9-062f-4a8c-98bb-a9f339617004"),
                            AddDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("86bab430-5e0a-4f62-9163-aeeb7aa9bc2a")
                        },
                        new
                        {
                            Id = new Guid("fceb1793-00ea-45fd-a382-96ddff800f80"),
                            AddDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("17591683-782c-4440-878a-7e286081a81e")
                        },
                        new
                        {
                            Id = new Guid("fc72d630-32ed-466b-b656-ae12c162b858"),
                            AddDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("a458d036-0f19-49cd-91ff-5ce9b7a19bc8")
                        },
                        new
                        {
                            Id = new Guid("b951b26f-33ad-4bc9-85d0-720ec6dc75d6"),
                            AddDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("599bab9c-6cb8-4196-9ceb-9afc74254247")
                        },
                        new
                        {
                            Id = new Guid("acdd34ab-9d95-4c6a-965c-d091a38912cd"),
                            AddDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("ed207dfa-d8ed-40f9-be96-24d5be74c9a9")
                        },
                        new
                        {
                            Id = new Guid("31629bf3-e0d8-4f5b-a894-972f02c34c82"),
                            AddDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("939eb2d4-439c-4491-956d-82b639aa42bc")
                        },
                        new
                        {
                            Id = new Guid("ed34af26-5ddb-4ca7-9dfd-6ef31468223e"),
                            AddDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("76e0e6b2-932e-450e-b944-86ccb7ff0bff")
                        },
                        new
                        {
                            Id = new Guid("c6bdcb5d-7ed1-4e1f-836e-67466a439c81"),
                            AddDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("4ef740ed-732e-4ca1-b404-80678ba6cbc1")
                        },
                        new
                        {
                            Id = new Guid("ad527ef9-d46c-4412-b1da-bd61267251b5"),
                            AddDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("f5a697d1-b2bf-40c9-863b-6bd43d27595d")
                        },
                        new
                        {
                            Id = new Guid("caaed764-45d1-4d30-871c-8add3daa9cdb"),
                            AddDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("7de0edfc-5e64-4d14-b38b-f5c0ba5ea34c")
                        },
                        new
                        {
                            Id = new Guid("49141ec8-3013-4bca-a5ac-e7997a51c9ab"),
                            AddDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("a68c09fe-11e3-4a52-b76b-b56151ea4a35")
                        },
                        new
                        {
                            Id = new Guid("ca3f0081-1bd8-40dc-b203-22570b4204ba"),
                            AddDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("7d9fdaf5-e7c4-4d91-aa1f-31bf51571c3a")
                        },
                        new
                        {
                            Id = new Guid("45470a25-94df-4e5a-a115-8ecbef97854e"),
                            AddDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("ea83e531-7985-4341-afdf-be9d43e79bfc")
                        },
                        new
                        {
                            Id = new Guid("01c1fa73-fda7-4cfa-9731-2d5a802e8da1"),
                            AddDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("a182168e-d522-4a08-b2d4-96080f7a80b8")
                        },
                        new
                        {
                            Id = new Guid("463ddd43-1e9f-477a-801a-7810ac9c73bd"),
                            AddDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("d8093abf-dcd5-449a-8754-f90c34fb3982")
                        },
                        new
                        {
                            Id = new Guid("8d584f03-9b01-424c-bc58-c0eb15fe7b63"),
                            AddDate = new DateTime(2024, 2, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("6457f588-6bf7-413f-9685-70ffd90e6ba6")
                        },
                        new
                        {
                            Id = new Guid("6ecbed1b-e95a-4bf9-a39f-b9551bbb6fb8"),
                            AddDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("a47b01b1-c7dc-4766-8f3c-ea0451b91741")
                        },
                        new
                        {
                            Id = new Guid("809fdebf-0c95-4c76-bad2-ce3fecdf37ef"),
                            AddDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("8541f399-22c4-4f04-a928-612b4a37edab")
                        },
                        new
                        {
                            Id = new Guid("e896ebeb-c913-49df-9792-4787b2d1de2b"),
                            AddDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Waiting",
                            TaskId = new Guid("24ce9f1c-0f6e-4c26-bf40-624535ec8730")
                        });
                });

            modelBuilder.Entity("TaskList.Domain.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TaskListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskListId");

                    b.ToTable("Task");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eceec90e-5144-4f28-808d-c7f2c1bef010"),
                            AddDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 1 листа Первый список задач",
                            Name = "Задача 1 листа Первый список задач",
                            TaskListId = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9")
                        },
                        new
                        {
                            Id = new Guid("de889a60-0f47-4341-acce-2414514d91a8"),
                            AddDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 2 листа Первый список задач",
                            Name = "Задача 2 листа Первый список задач",
                            TaskListId = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9")
                        },
                        new
                        {
                            Id = new Guid("bd3cf78d-82c4-4bd3-b575-76ae7a4b9197"),
                            AddDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 3 листа Первый список задач",
                            Name = "Задача 3 листа Первый список задач",
                            TaskListId = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9")
                        },
                        new
                        {
                            Id = new Guid("c5607256-205a-48c7-8b4f-c7fa4bd684cc"),
                            AddDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 4 листа Первый список задач",
                            Name = "Задача 4 листа Первый список задач",
                            TaskListId = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9")
                        },
                        new
                        {
                            Id = new Guid("5561d361-33ba-4bf0-8c9d-f5f035bf9807"),
                            AddDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 5 листа Первый список задач",
                            Name = "Задача 5 листа Первый список задач",
                            TaskListId = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9")
                        },
                        new
                        {
                            Id = new Guid("a19cff3c-921f-4b73-b482-27aca75eaae3"),
                            AddDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 6 листа Первый список задач",
                            Name = "Задача 6 листа Первый список задач",
                            TaskListId = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9")
                        },
                        new
                        {
                            Id = new Guid("6b4bbae9-2200-49b7-8f2f-d1f240050cec"),
                            AddDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 7 листа Первый список задач",
                            Name = "Задача 7 листа Первый список задач",
                            TaskListId = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9")
                        },
                        new
                        {
                            Id = new Guid("6e17e8f2-620e-4bab-b4b2-971d1acc9be2"),
                            AddDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 8 листа Первый список задач",
                            Name = "Задача 8 листа Первый список задач",
                            TaskListId = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9")
                        },
                        new
                        {
                            Id = new Guid("865430dd-32fe-4673-93db-f18a29e9a1b8"),
                            AddDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 9 листа Первый список задач",
                            Name = "Задача 9 листа Первый список задач",
                            TaskListId = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9")
                        },
                        new
                        {
                            Id = new Guid("88f9453d-301b-4f3f-a1f7-50087e98c3c5"),
                            AddDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 10 листа Первый список задач",
                            Name = "Задача 10 листа Первый список задач",
                            TaskListId = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9")
                        },
                        new
                        {
                            Id = new Guid("d4e7ff20-43dd-430d-9fcb-ad8523f62b0c"),
                            AddDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 1 листа Второй список задач",
                            Name = "Задача 1 листа Второй список задач",
                            TaskListId = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833")
                        },
                        new
                        {
                            Id = new Guid("86bab430-5e0a-4f62-9163-aeeb7aa9bc2a"),
                            AddDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 2 листа Второй список задач",
                            Name = "Задача 2 листа Второй список задач",
                            TaskListId = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833")
                        },
                        new
                        {
                            Id = new Guid("17591683-782c-4440-878a-7e286081a81e"),
                            AddDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 3 листа Второй список задач",
                            Name = "Задача 3 листа Второй список задач",
                            TaskListId = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833")
                        },
                        new
                        {
                            Id = new Guid("a458d036-0f19-49cd-91ff-5ce9b7a19bc8"),
                            AddDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 4 листа Второй список задач",
                            Name = "Задача 4 листа Второй список задач",
                            TaskListId = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833")
                        },
                        new
                        {
                            Id = new Guid("599bab9c-6cb8-4196-9ceb-9afc74254247"),
                            AddDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 5 листа Второй список задач",
                            Name = "Задача 5 листа Второй список задач",
                            TaskListId = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833")
                        },
                        new
                        {
                            Id = new Guid("ed207dfa-d8ed-40f9-be96-24d5be74c9a9"),
                            AddDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 6 листа Второй список задач",
                            Name = "Задача 6 листа Второй список задач",
                            TaskListId = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833")
                        },
                        new
                        {
                            Id = new Guid("939eb2d4-439c-4491-956d-82b639aa42bc"),
                            AddDate = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 7 листа Второй список задач",
                            Name = "Задача 7 листа Второй список задач",
                            TaskListId = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833")
                        },
                        new
                        {
                            Id = new Guid("76e0e6b2-932e-450e-b944-86ccb7ff0bff"),
                            AddDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 8 листа Второй список задач",
                            Name = "Задача 8 листа Второй список задач",
                            TaskListId = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833")
                        },
                        new
                        {
                            Id = new Guid("4ef740ed-732e-4ca1-b404-80678ba6cbc1"),
                            AddDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 9 листа Второй список задач",
                            Name = "Задача 9 листа Второй список задач",
                            TaskListId = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833")
                        },
                        new
                        {
                            Id = new Guid("f5a697d1-b2bf-40c9-863b-6bd43d27595d"),
                            AddDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 10 листа Второй список задач",
                            Name = "Задача 10 листа Второй список задач",
                            TaskListId = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833")
                        },
                        new
                        {
                            Id = new Guid("7de0edfc-5e64-4d14-b38b-f5c0ba5ea34c"),
                            AddDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 1 листа Третий список задач",
                            Name = "Задача 1 листа Третий список задач",
                            TaskListId = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6")
                        },
                        new
                        {
                            Id = new Guid("a68c09fe-11e3-4a52-b76b-b56151ea4a35"),
                            AddDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 2 листа Третий список задач",
                            Name = "Задача 2 листа Третий список задач",
                            TaskListId = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6")
                        },
                        new
                        {
                            Id = new Guid("7d9fdaf5-e7c4-4d91-aa1f-31bf51571c3a"),
                            AddDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 3 листа Третий список задач",
                            Name = "Задача 3 листа Третий список задач",
                            TaskListId = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6")
                        },
                        new
                        {
                            Id = new Guid("ea83e531-7985-4341-afdf-be9d43e79bfc"),
                            AddDate = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 4 листа Третий список задач",
                            Name = "Задача 4 листа Третий список задач",
                            TaskListId = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6")
                        },
                        new
                        {
                            Id = new Guid("a182168e-d522-4a08-b2d4-96080f7a80b8"),
                            AddDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 5 листа Третий список задач",
                            Name = "Задача 5 листа Третий список задач",
                            TaskListId = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6")
                        },
                        new
                        {
                            Id = new Guid("d8093abf-dcd5-449a-8754-f90c34fb3982"),
                            AddDate = new DateTime(2024, 2, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 6 листа Третий список задач",
                            Name = "Задача 6 листа Третий список задач",
                            TaskListId = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6")
                        },
                        new
                        {
                            Id = new Guid("6457f588-6bf7-413f-9685-70ffd90e6ba6"),
                            AddDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 7 листа Третий список задач",
                            Name = "Задача 7 листа Третий список задач",
                            TaskListId = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6")
                        },
                        new
                        {
                            Id = new Guid("a47b01b1-c7dc-4766-8f3c-ea0451b91741"),
                            AddDate = new DateTime(2024, 2, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 8 листа Третий список задач",
                            Name = "Задача 8 листа Третий список задач",
                            TaskListId = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6")
                        },
                        new
                        {
                            Id = new Guid("8541f399-22c4-4f04-a928-612b4a37edab"),
                            AddDate = new DateTime(2024, 2, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 9 листа Третий список задач",
                            Name = "Задача 9 листа Третий список задач",
                            TaskListId = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6")
                        },
                        new
                        {
                            Id = new Guid("24ce9f1c-0f6e-4c26-bf40-624535ec8730"),
                            AddDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Описание задачи 10 листа Третий список задач",
                            Name = "Задача 10 листа Третий список задач",
                            TaskListId = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6")
                        });
                });

            modelBuilder.Entity("TaskList.Domain.Entities.TaskListEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TaskList");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00a4b751-07f5-437a-b6da-8f5fcec4bdc9"),
                            Description = "Описание первого списка задач",
                            Name = "Первый список задач",
                            Owner = "user@example.com"
                        },
                        new
                        {
                            Id = new Guid("04d38219-3cf3-4bf4-9604-f54a7f244833"),
                            Description = "Описание второго списка задач",
                            Name = "Второй список задач",
                            Owner = "user@example.com"
                        },
                        new
                        {
                            Id = new Guid("f395367c-ddb7-40e2-ba9c-844c3965adf6"),
                            Description = "Описание третьего списка задач",
                            Name = "Третий список задач",
                            Owner = "user@example.com"
                        });
                });

            modelBuilder.Entity("TaskList.Domain.Entities.CommentEntity", b =>
                {
                    b.HasOne("TaskList.Domain.Entities.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskList.Domain.Entities.StatusTaskHistory", b =>
                {
                    b.HasOne("TaskList.Domain.Entities.TaskEntity", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskList.Domain.Entities.TaskEntity", b =>
                {
                    b.HasOne("TaskList.Domain.Entities.TaskListEntity", "TaskList")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TaskList");
                });

            modelBuilder.Entity("TaskList.Domain.Entities.TaskListEntity", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
